- name: Install dotfiles
  hosts: localhost
  roles:
    - role: gbraad.dotfiles
      vars:
        user: gbraad

    - role: gbraad.dotfiles-devenv
      vars:
        prefix: dotfedora
        command: exec
        args: cat /etc/os-release
